#name: xeus-kernel
#channels:
#  - https://repo.mamba.pm/emscripten-forge
#  - conda-forge
#dependencies:
#  - python=3.11
#  - xeus-python
#  - ipycanvas

name: xeus-r-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-r >= 0.4.0
  - r-coursekata
  - r-colorspace




